### ISSUE TITLE
Getting Invalid DN Syntax on login

### ISSUE THREAD

**Issue by Joan-Rojo1** [ldaptools/ldaptools-bundle#22] opened 2017-07-24 14:45 UTC
Hi there,

This is my first first experience with this and I figure out I should be missing some basics, but...first, context. I am using LdapGuard for logging over FOSUserBundle, the connection is established with OpenLDAP Server and with FOSUserBundle DB but when I try any login I always get Invalid DN Syntax. 

I've tried to write directly on vendor's LdapGuardAuthenticator and change on checkCredentials method this line:

$response = $this->ldap->getConnection()->execute(
                new AuthenticationOperation($user->getUsername(), $credentials['password'])
            );

with my dev LDAP server admin account credentials:

$response = $this->ldap->getConnection()->execute(
                new AuthenticationOperation('cn=admin,dc=example,dc=org', 'p@ssword')
            );

And it works OK ($response->isAuthenticated() is true then) but when I try with a login with a FOSUserBundle DB user, I dump the user according with the $credentials before the line ... if (!$response->isAuthenticated()) ... and the user seems to be which I'am looking for but it returns the 'Invalid DN syntax' message and is not authenticated.

In addition, if needed I share part of my config.yml and my security.yml:

config.yml:

ldap_tools:
    domains:
        publico.es:
            domain_name: example.org
            base_dn: 'dc=example,dc=org'
            username: 'cn=admin,dc=example,dc=org'
            password: p@ssword
            servers: [local.example.org]
            ldap_type: openldap

    security:
        guard:
            # This is the entry point/start path route name for the RedirectResponse of the Guard component
            #start_path: '/login'
            default_target_path: '/login/'
            always_use_target_path: false
            target_path_parameter: '_target_path'
            use_referrer: false
            failure_path: null
            failure_forward: false
            failure_path_parameter: '_failure_path'
            remember_me: true
        # Set this to true if you want user attributes re-queried on each request.
        refresh_user_attributes: true
        # Set this to true if you want user roles re-queried on each request.
        refresh_user_roles: true

security.yml:

firewalls:
        main:
            anonymous:  ~
            # Using the FOSUserBundle provider to find the users...
            provider: fos_userbundle
            # provider: ldap
            form_login:
                login_path: login
                check_path: login_check
                #user_forward: true
            pattern: ^/login
            logout:     ~
            guard:
                authenticators:
                    - ldap_tools.security.ldap_guard_authenticator

Thanks in advance & kind regards anyway,

**Comment by ChadSikorra** [comment] 2017-07-24 15:06
This is related to https://github.com/ldaptools/ldaptools-bundle/issues/20. The problem is that OpenLDAP expects a Distinguished Name for the bind username. There are a few ways around this currently. If all your users are in a specific container in LDAP, you could set a `bind_format`:

```yaml
ldap_tools:
    domains:
        publico.es:
            domain_name: example.org
            base_dn: 'dc=example,dc=org'
            username: 'cn=admin,dc=example,dc=org'
            password: p@ssword
            servers: [local.example.org]
            ldap_type: openldap
            bind_format: "CN=%username%,DC=example,DC=org"
```

Another option would be to use the [LdapTools Authentication Event](https://github.com/ldaptools/ldaptools/blob/master/docs/en/reference/Events.md#the-ldap-authentication-event) and manually set the username on the event object using the `setUsername($dn)` setter, after querying LDAP for the DN of the user based off a common name/username.

I plan on making this less painful to configure in the next release.

**Comment by Joan-Rojo1** [comment] 2017-07-24 17:30
Hi Chad,

I have been able to log in, but overwritten the DN on checkCredentials method on vendor.

It would be fine to do it by adding bind_format but I get a fatal error since the parameter username does not exist (log says). I thought that the value of that username should replaced by the bundle, but never being a 'common' parameter. Should it be created or so?

Respect to the second option, by now, all this is implemented 'automaticly' by YML configuration files.  What should be the way to start to do that? I mean, what class to extend or anything else. Any guide?

Really appreciated, thank you!

**Comment by ChadSikorra** [comment] 2017-07-24 19:06
You might have to escape the `%` since it has special meaning in Symfony config. Probably: `bind_format: "CN=%%username%%,DC=example,DC=org"`. An example of the events method would be here:

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/LDAP-Events.md#the-service-event-subscriber-method

You would want to use the `Event::LDAP_AUTHENTICATION_BEFORE` event in the subscriber. And use the `LdapAuthenticationEvent` in the event method itself.

**Comment by ChadSikorra** [comment] 2017-08-13 16:37
This has been fixed with https://github.com/ldaptools/ldaptools-bundle/commit/cab368a236f26d0927ccba270e6d65db15d2c008. You can either set the `bind_format` option or the `login_query_attribute` option to form the username when you are using a user class or user provider that is not from this bundle. More information is documented here:

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/LDAP-Authentication-Provider.md#ldap-authentication-username
https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/Configuration-Reference.md#login_query_attribute

**Closed by ChadSikorra** 2017-08-13 16:37 UTC
